server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://user-postgres:5432/users
    username: user
    password: user

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/booking-platform
